import type { Metadata } from "next";
import { Inter, Satisfy, Roboto_Mono } from "next/font/google";
import { Children } from "@/types";
import "@/styles/globals.css";
import ThemeProvider from "@/contexts/use-theme";
import Main from "./_components/main";

const inter = Inter({ subsets: ["latin"] });
export const roboto = Roboto_Mono({ subsets: ["latin"] });
export const satisfy = Satisfy({ subsets: ["latin"], weight: "400" });

const metadata: Metadata = {
  title: "Portfolio | Jazztine Cruz",
  description: "Portfolio generated by NextJS and ReactJS",
};

type Props = {
  children: Children;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <ThemeProvider>
          <Main>{children}</Main>
        </ThemeProvider>
      </body>
    </html>
  );
};
export default RootLayout;
