import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Children } from "@/types";
import "@/styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: Children;
};

const RootLayout = ({ children }: Props) => {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
};
export default RootLayout;
